In [1]:
pwd

'/content'

In [2]:
# importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import math
from scipy import stats
import matplotlib.dates as mdates
from plotly import tools
import plotly.tools as tls
import plotly.figure_factory as ff
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, plot, iplot
import statsmodels.api as sm
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller
from sklearn.metrics import mean_squared_error
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [3]:
df = pd.read_csv('Time_series_analysis_and_forecast_DATASET.csv')
df.head()

              FullDate  Tmax   SysLoad  GasPrice  ElecPrice
0  2010-09-01 00:00:00  15.8  1688.215      3.69     23.710
1  2010-09-01 01:00:00  15.8  1669.195      3.69     22.635
2  2010-09-01 02:00:00  15.8  1491.980      3.69     22.565
3  2010-09-01 03:00:00  15.8  1330.760      3.69     18.910
4  2010-09-01 04:00:00  15.8  1247.940      3.69     18.030

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92016 entries, 0 to 92015
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   FullDate   92016 non-null  object
 1   Tmax       92016 non-null  float64
 2   SysLoad    92016 non-null  float64
 3   GasPrice   92016 non-null  float64
 4   ElecPrice  92016 non-null  float64
dtypes: float64(4), object(1)
memory usage: 3.5+ MB

In [6]:
df['FullDate'] = pd.to_datetime(df['FullDate'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92016 entries, 0 to 92015
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   FullDate   92016 non-null  datetime64[ns]
 1   Tmax       92016 non-null  float64
 2   SysLoad    92016 non-null  float64
 3   GasPrice   92016 non-null  float64
 4   ElecPrice  92016 non-null  float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 3.5 MB

In [9]:
df = df.rename(columns={"FullDate": "ds", "ElecPrice": "y"})

In [10]:
df.head()

                   ds  Tmax   SysLoad  GasPrice       y
0 2010-09-01 00:00:00  15.8  1688.215      3.69  23.710
1 2010-09-01 01:00:00  15.8  1669.195      3.69  22.635
2 2010-09-01 02:00:00  15.8  1491.980      3.69  22.565
3 2010-09-01 03:00:00  15.8  1330.760      3.69  18.910
4 2010-09-01 04:00:00  15.8  1247.940      3.69  18.030

In [16]:
df = df.sort_values('ds')

In [17]:
df.head()

                   ds  Tmax   SysLoad  GasPrice       y
0 2010-09-01 00:00:00  15.8  1688.215      3.69  23.710
1 2010-09-01 01:00:00  15.8  1669.195      3.69  22.635
2 2010-09-01 02:00:00  15.8  1491.980      3.69  22.565
3 2010-09-01 03:00:00  15.8  1330.760      3.69  18.910
4 2010-09-01 04:00:00  15.8  1247.940      3.69  18.030

In [14]:
!pip install prophet

Requirement already satisfied: prophet in /usr/local/lib/python3.10/dist-packages (1.1.4)
Requirement already satisfied: cmdstanpy>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from prophet) (1.1.0)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.10/dist-packages (from prophet) (1.22.4)
Requirement already satisfied: matplotlib>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from prophet) (3.7.1)
Requirement already satisfied: pandas>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from prophet) (1.5.3)
Requirement already satisfied: LunarCalendar>=0.0.9 in /usr/local/lib/python3.10/dist-packages (from prophet) (0.0.9)
Requirement already satisfied: convertdate>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from prophet) (2.4.0)
Requirement already satisfied: holidays>=0.25 in /usr/local/lib/python3.10/dist-packages (from prophet) (0.29)
Requirement already satisfied: python-dateutil>=2.8.0 in /usr/local/lib/python3.10/dist-packages (from prophet) (2.8.2)
Requirement already satisfied: tqdm>=4.36.1 in /usr/local/lib/python3.10/dist-packages (from prophet) (4.65.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from prophet) (6.0.0)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.10/dist-packages (from convertdate>=2.1.2->prophet) (0.5.12)
Requirement already satisfied: ephem>=3.7.5.3 in /usr/local/lib/python3.10/dist-packages (from LunarCalendar>=0.0.9->prophet) (4.1.4)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from LunarCalendar>=0.0.9->prophet) (2022.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (4.41.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (8.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=2.0.0->prophet) (3.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.0->prophet) (1.16.0)

In [15]:

import prophet

In [18]:
train_set = df[:2757]
test_set = df[2757:]

In [20]:
from prophet import Prophet

In [21]:
model = Prophet()
model.fit(train_set)

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpba7xtvq7/z7c6fact.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpba7xtvq7/jr57oa5o.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=33968', 'data', 'file=/tmp/tmpba7xtvq7/z7c6fact.json', 'init=/tmp/tmpba7xtvq7/jr57oa5o.json', 'output', 'file=/tmp/tmpba7xtvq7/prophet_model4x5hb9f_/prophet_model-20230725202738.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
20:27:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
20:27:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

In [22]:
# Create a DataFrame to store the predictions
future = model.make_future_dataframe(periods=len(test_set))
# Make predictions on the future DataFrame
forecast = model.predict(future)

# Extract the relevant columns for evaluation
predicted_prices = forecast['yhat'].tail(len(test_set))

In [23]:
forecast.head()

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,daily,daily_lower,daily_upper,weekly,weekly_lower,weekly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2010-09-01 00:00:00,37.778618,-77.255784,181.439567,37.778618,37.778618,7.711576,7.711576,7.711576,0.308831,0.308831,0.308831,7.402745,7.402745,7.402745,0.0,0.0,0.0,45.490194
1,2010-09-01 01:00:00,37.723564,-83.452542,166.688026,37.723564,37.723564,6.711908,6.711908,6.711908,-1.575023,-1.575023,-1.575023,8.286931,8.286931,8.286931,0.0,0.0,0.0,44.435471
2,2010-09-01 02:00:00,37.668509,-97.102734,171.020071,37.668509,37.668509,3.172552,3.172552,3.172552,-5.998068,-5.998068,-5.998068,9.170621,9.170621,9.170621,0.0,0.0,0.0,40.841062
3,2010-09-01 03:00:00,37.613455,-95.014099,163.159697,37.613455,37.613455,-0.808399,-0.808399,-0.808399,-10.851834,-10.851834,-10.851834,10.043435,10.043435,10.043435,0.0,0.0,0.0,36.805056
4,2010-09-01 04:00:00,37.558400,-90.013770,155.619692,37.558400,37.558400,-3.294304,-3.294304,-3.294304,-14.189270,-14.189270,-14.189270,10.894966,10.894966,10.894966,0.0,0.0,0.0,34.264097

In [25]:
predicted_prices.head()

2757     1.707180
2758     9.018625
2759    18.276334
2760    18.148763
2761    28.718137
Name: yhat, dtype: float64

In [27]:
from sklearn.metrics import mean_absolute_error

In [29]:
mse=mean_absolute_error(predicted_prices,test_set['y'])

In [30]:
import numpy as np

In [31]:
np.sqrt(mse)

109.93507103347255